name: Build and testing parKVFinder

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build-n-test:
    name: Build binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-15]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == macos* ]]; then
            brew install llvm
            brew install libomp
          fi
      
      - name: Build parKVFinder binary in ${{ matrix.os }}
        run: |
          /opt/homebrew/opt/llvm/bin/clang -Isrc -c src/utils.c
      
      - name: Integration testing
        run: |
          # export KVFinder_PATH=/home/runner/work/parKVFinder/parKVFinder
          # bash tests/testing.sh
          # cat input/KV_Files/1FMO/1FMO.KVFinder.results.toml
